import { images } from '@/assets/images';

const {
  model_1082,
  model_1083,
  model_1086,
  model_1088,
  model_1091,
  model_1093,
  model_1095,
  model_1098,
  model_1101,
  model_1103,
  model_1104,
  model_1106,
  model_1107,
  model_1108,
  model_1116,
  model_1122,
  model_1123,
  model_1126,
  model_1127,
  model_1130,
  model_sea_1,
  model_sea_2,
  model_sea_3,
  model_sea_4,
  model_sea_5,
  model_sea_6,
  model_sea_7,
  model_sea_8,
} = images;

export const photos = [
  {
    src: model_1082.src,
    width: 2,
    height: 3,
    alt: 'Black and white photo of a model sitting on the floor, wearing black pants and a white shirt',
    key: '0',
  },
  {
    src: model_1083.src,
    width: 2,
    height: 3,
    alt: 'Black and white photo of a smiling model sitting on the sofa',
    key: '1',
  },
  {
    src: model_1086.src,
    width: 2,
    height: 3,
    alt: 'Black and white photo of a model with large stylish earrings',
    key: '2',
  },

  {
    src: model_1088.src,
    width: 2,
    height: 3,
    alt: 'Black and white photo of a model sitting on the sofa',
    key: '3',
  },
  {
    src: model_1091.src,
    width: 2,
    height: 3,
    alt: 'Black and white photo of a smiling model in a white shirt',
    key: '4',
  },

  {
    src: model_1093.src,
    width: 2,
    height: 3,
    alt: 'Black and white photo of a model wearing black jacket and a white shirt with stylish accessories',
    key: '5',
  },
  {
    src: model_1095.src,
    width: 2,
    height: 3,
    alt: 'Photo of a model sitting in the armchair, wearing black pants and a white shirt',
    key: '6',
  },
  {
    src: model_1098.src,
    width: 2,
    height: 3,
    alt: 'Photo of a model standing near wooden bar stool. The model is wearing in a black suit and a white blouse',
    key: '7',
  },
  {
    src: model_1101.src,
    width: 2,
    height: 3,
    alt: 'Photo of a standing model. The model is wearing in a black suit and a white blouse',
    key: '8',
  },

  {
    src: model_1103.src,
    width: 2,
    height: 3,
    alt: 'Photo of a model sitting on the floor, wearing black suit and a white shirt',
    key: '9',
  },

  {
    src: model_1104.src,
    width: 2,
    height: 3,
    alt: 'Photo of a model sitting on a chair, wearing  a white shirt and a black pants',
    key: '10',
  },

  {
    src: model_1106.src,
    width: 2,
    height: 3,
    alt: 'Photo of a model sitting on the chair, wearing black pants and a white shirt,  , with bright sunlight streaming in through the window',
    key: '11',
  },
  {
    src: model_1107.src,
    width: 2,
    height: 3,
    alt: 'Photo of a standing model. The model is wearing in a black suit, a white blouse , and high-heeled shoes.',
    key: '12',
  },
  {
    src: model_1108.src,
    width: 2,
    height: 3,
    alt: 'A model with bare feet, dressed in a light dress, is sitting on the sofa',
    key: '13',
  },
  {
    src: model_1116.src,
    width: 2,
    height: 3,
    alt: 'A model with bare feet, dressed in a light dress, is sitting on the floor near the sofa',
    key: '14',
  },
  {
    src: model_1122.src,
    width: 2,
    height: 3,
    alt: 'A model dressed in a light dress, is seated, leaning back on the sofa.',
    key: '15',
  },
  {
    src: model_1123.src,
    width: 2,
    height: 3,
    alt: 'A smiling model dressed in a red dress, is seating on a wooden bar stool.',
    key: '16',
  },
  {
    src: model_1126.src,
    width: 2,
    height: 3,
    alt: 'A  model dressed in a red dress, wearing glasses.',
    key: '17',
  },
  {
    src: model_1127.src,
    width: 2,
    height: 3,
    alt: 'A model with bare feet, dressed in a white shirt and black pants, is sitting on the floor',
    key: '18',
  },
  {
    src: model_1130.src,
    width: 2,
    height: 3,
    alt: 'A model with bare feet, dressed in a white shirt and black pants, is standing by the window.',
    key: '19',
  },

  {
    src: model_sea_1.src,
    width: 2,
    height: 3,
    alt: 'A model in a black swimsuit on the seashore in the rocks, monochrome photo',
    key: '20',
  },
  {
    src: model_sea_2.src,
    width: 2,
    height: 3,
    alt: 'A model in a black swimsuit on the seashore in the rocks.',
    key: '21',
  },
  {
    src: model_sea_3.src,
    width: 2,
    height: 3,
    alt: 'A model in green dress on the seashore.',
    key: '22',
  },
  {
    src: model_sea_4.src,
    width: 2,
    height: 3,
    alt: 'A model on the seashore, monochrome photo',
    key: '23',
  },
  {
    src: model_sea_5.src,
    width: 2,
    height: 3,
    alt: 'A model in a black swimsuit leans on a rock by the sea',
    key: '24',
  },
  {
    src: model_sea_6.src,
    width: 2,
    height: 3,
    alt: 'A model in a black swimsuit on the seashore next to a rock, monochrome photo.',
    key: '25',
  },
  {
    src: model_sea_7.src,
    width: 2,
    height: 3,
    alt: 'A model in a black swimsuit on the seashore next to a rock',
    key: '26',
  },
  {
    src: model_sea_8.src,
    width: 2,
    height: 3,
    alt: 'A model in a black swimsuit lies on the seashore',
    key: '27',
  },
];
